raw_csv = 'data/1_raw'
min_max_csv = 'data/3_scaled/min_max_values.csv'
rows_to_skip = 17
start_year = 2012
end_year = 2025
features = ['O3', 'NO', 'NO2', 'PM10', 'PM2.5', 'wind_speed', 'temp', 'wind_dir_sin', 'wind_dir_cos']
pollutants = ['CO', 'O3', 'NO', 'NO2', 'PM10', 'PM2.5']
scaled_csv = 'data/3_scaled/scaled.csv'
unscaled_csv = 'data/2_unscaled/unscaled.csv'